name: GatherMidwest
favicon: null
layout_spectrum: 0.1511103310622275
typography_spectrum: 0.5241184064652771
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7248007133603096
  lightness: 0.15260322205722332
  saturation: 0.6341904334258288
  rhythmicContrast: 0.4117986436467618
purpose: []
