name: GatherMidwest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5241184064652771
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e2934'
    - '#feff00'
    - '#fa9c53'
    - '#fdfffd'
    - '#f64c10'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
